apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cherrypicker
  labels:
    app: cherrypicker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cherrypicker
  template:
    metadata:
      labels:
        app: cherrypicker
    spec:
      terminationGracePeriodSeconds: 180
      containers:
        - name: cherrypicker
          image: gcr.io/prow-clarketm/cherrypicker:v20200430-6975cacbc
          args:
            - --dry-run=false
            - --use-prow-assignments=false
            - "--labels=cla: yes"
            - --create-issue-on-failure=true
            - --github-endpoint=http://ghproxy
            - --github-endpoint=https://api.github.com
          ports:
            - name: http
              containerPort: 8888
          volumeMounts:
            - name: hmac
              mountPath: /etc/webhook
              readOnly: true
            - name: oauth
              mountPath: /etc/github
              readOnly: true
      volumes:
        - name: hmac
          secret:
            secretName: hmac-token
        - name: oauth
          secret:
            secretName: oauth-token
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cherrypicker
  namespace: default
  name: cherrypicker
spec:
  selector:
    app: cherrypicker
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP