prowjob_namespace: default
pod_namespace: test-pods
log_level: debug

plank:
  job_url_template: 'https://prow.travismclarke.com/view/gcs/prow-clarketm{{if eq .Spec.Type "presubmit"}}/pr-logs/pull/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/pr-logs/pull/batch{{else}}/logs{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}'
  job_url_prefix_config:
    '*': https://prow.travismclarke.com/view/gcs/
    prow-clarketm/sample: https://prow-private.travismclarke.com/view/gcs/
  pod_pending_timeout: 60m
  default_decoration_configs:
    '*':
      utility_images: # using the tag we identified above
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20200409-becd20a71"
        initupload: "gcr.io/k8s-prow/initupload:v20200409-becd20a71"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20200409-becd20a71"
        sidecar: "gcr.io/k8s-prow/sidecar:v20200409-becd20a71"
      gcs_configuration:
        bucket: prow-clarketm     # the bucket we just made
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials # the secret we just made
      timeout: 4m
      #    cookiefile_secret: "abc"
#      datetime_format: "2006-01-02T15:04:05Z07:00"

sinker:
  resync_period: 15m
  max_prowjob_age: 48h
  max_pod_age: 30m

deck:
  hidden_repos:
    - prow-clarketm/sample
  spyglass:
    size_limit: 500000000 # 500MB
    gcs_browser_prefix: https://gcsweb.k8s.io/gcs/
    viewers:
      "started.json|finished.json":
        - "metadata"
      "build-log.txt":
        - "buildlog"
      "artifacts/junit.*\\.xml":
        - "junit"
      "artifacts/filtered.cov":
        - "coverage"
    announcement: "This page -- spyglass -- is the default viewer for prow.{{if .ArtifactPath}} For now, the deprecated gubernator page spyglass replaces <a href='https://gubernator.k8s.io/build/{{.ArtifactPath}}'>remains available</a>.{{end}}"
  rerun_auth_configs:
    '*':
      allow_anyone: true
    prow-clarketm/prow:
      github_users:
        - billybob

tide:
  sync_period: 2m
  queries:
    - orgs:
        - prow-clarketm
      labels:
        - lgtm
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/blocked-paths
        - do-not-merge/hold
        - do-not-merge/invalid-commit-message
        - do-not-merge/invalid-owners-file
        - do-not-merge/release-note-label-needed
        - do-not-merge/work-in-progress
        - needs-rebase
  blocker_label: tide/merge-blocker
  squash_label: tide/merge-method-squash
  rebase_label: tide/merge-method-rebase
  merge_label: tide/merge-method-merge
  merge_method:
    prow-clarketm: squash
  merge_commit_template:
    prow-clarketm:
      body: "Co-authored-by: {{.Author.Login}} <{{.Author.Login}}@users.noreply.github.com>"

branch-protection:
  orgs:
    prow-clarketm:
      allow_force_pushes: true
      protect: true
      repos:
        prow:
          protect: false
          branches:
            master:
              protect: true
            dev:
              protect: true
          restrictions: # only allow admins
            users:
              - j-orangeman
            teams: []
          required_pull_request_reviews:
            required_approving_review_count: 1
        sample:
          allow_force_pushes: true
          protect: true
          required_pull_request_reviews:
            required_approving_review_count: 1

slack_reporter_configs:
  '*':
    job_types_to_report:
      - presubmit
      - postsubmit
      - periodic
    job_states_to_report:
      - failure
      - error
    channel: test-failures
    report_template: "Job *{{.Spec.Job}}* of type *{{.Spec.Type}}* ended with state *{{.Status.State}}*. <{{.Status.URL}}|View logs>"
  prow-clarketm/prow:
    job_types_to_report:
      - presubmit
      - postsubmit
      - periodic
    job_states_to_report:
      - success
      - failure
      - error
    channel: test-failures
    report_template: "Job *{{.Spec.Job}}* of type *{{.Spec.Type}}* ended with state *{{.Status.State}}*. <{{.Status.URL}}|View logs>"

github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

periodics:
  #  - interval: 1m
  #    name: broken-cluster-test
  #    cluster: build2
  #    decorate: true
  #    spec:
  #      containers:
  #        - image: alpine
  #          command: ["sleep", "100"]
  - interval: 15m
    name: echo-test
    cluster: build
    decorate: true
    decoration_config:
      timeout: 3m
      #      datetime_format: "-"
      cookiefile_secret: ""
    spec:
      containers:
        - image: alpine
          command: ["ping", "-c", "10", "www.google.com"]
  - interval: 15m
    name: echo-test2
    cluster: default
    decorate: true
    decoration_config:
      timeout: 2m
    #      datetime_format: ""
    spec:
      containers:
        - image: alpine
          command: ["ping", "-c", "10", "www.google.com"]
  - interval: 15m
    name: echo-test3
    decorate: true
    spec:
      containers:
        - image: alpine
          command: ["ping", "-c", "10", "www.google.com"]
  - interval: 15m
    name: echo-test4
    decorate: true
    spec:
      containers:
        - image: alpine
          command: ["ping"]
          args: ["-c", "10", "www.google.com"]
  - interval: 15m
    name: echo-test5a
    decorate: true
    rerun_auth_config:
      github_users:
        - clarketm
    spec:
      containers:
        - image: gcr.io/slchase-canary/transfigure
          command: ["bash"]
          args: ["-c", "echo hello"]
  - interval: 15m
    name: echo-test5b
    decorate: true
    spec:
      containers:
        - image: gcr.io/slchase-canary/transfigure
          command: ["sh"]
          args: ["-c", "echo hello"]
  - interval: 15m
    name: echo-test5c
    decorate: true
    spec:
      containers:
        - image: gcr.io/slchase-canary/transfigure
          command: ["echo"]
          args: ["hello"]
  - interval: 15m
    name: echo-test6
    decorate: true
    spec:
      containers:
        - image: alpine
          command: ["echo", "hello"]
          args: ["world"]
  - interval: 15m
    name: echo-test7
    decorate: true
    spec:
      containers:
        - image: alpine
          command: ["sh"]
          args: ["-c", "echo hello"]
  - interval: 1m
    name: echo-test8
    decorate: true
    spec:
      containers:
        - image: alpine
          args: ["echo", "hello"]
#  - interval: 1m
#    name: failure
#    decorate: true
#    spec:
#      containers:
#        - image: alpine
#          command: ["false"]

postsubmits:
  prow-clarketm/prow:
    - name: test-postsubmit
      decorate: true
      spec:
        containers:
          - image: alpine
            command: ["/bin/printenv"]
    - name: test-postsubmit2
      decorate: true
      spec:
        containers:
          - image: alpine
            command: ["/bin/date"]

presubmits:
  prow-clarketm/prow:
    - name: test-presubmit
      decorate: true
      always_run: true
      skip_report: false
      rerun_auth_config:
        github_users:
          - j-orangeman
      spec:
        containers:
          - image: alpine
            command: ["/bin/ls"]
    - name: test-presubmit2
      decorate: true
      always_run: true
      skip_report: false
      spec:
        containers:
          - image: alpine
            command: ["/bin/ls"]
    - name: test-presubmit3
      decorate: true
      always_run: true
      skip_report: false
      spec:
        containers:
          - image: alpine
            command: ["/bin/ls"]

  #    - name: test-presubmit-fail
  #      decorate: true
  #      optional: true
  #      always_run: true
  #      skip_report: false
  #      spec:
  #        containers:
  #          - image: alpine
  #            command: ["/bin/bash", "-c", "exit 1"]

