prowjob_namespace: default
pod_namespace: test-pods
log_level: debug

plank:
  default_decoration_config:
    utility_images: # using the tag we identified above
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190715-1dacc7e01"
      initupload: "gcr.io/k8s-prow/initupload:v20190715-1dacc7e01"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190715-1dacc7e01"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190715-1dacc7e01"
    gcs_configuration:
      bucket: prow-clarketm	 # the bucket we just made
      path_strategy: explicit
    gcs_credentials_secret: gcs-credentials # the secret we just made

github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

periodics:
  - interval: 10m
    name: echo-test
    decorate: true
    spec:
      containers:
        - image: alpine
          command: ["/bin/date"]

postsubmits:
  prow-clarketm/prow:
    - name: test-postsubmit
      decorate: true
      spec:
        containers:
          - image: alpine
            command: ["/bin/printenv"]
    - name: test-postsubmit2
      decorate: true
      spec:
        containers:
          - image: alpine
            command: ["/bin/date"]
  prow-clarketm/sample:
    - name: test-postsubmit3
      decorate: true
      spec:
        containers:
          - image: alpine
            command: ["/bin/date"]

presubmits:
  prow-clarketm/prow:
    - name: test-presubmit
      decorate: true
      always_run: true
      skip_report: false
      spec:
        containers:
          - image: alpine
            command: ["/bin/printenv"]
    - name: test-presubmit2
      decorate: true
      always_run: true
      skip_report: false
      spec:
        containers:
          - image: alpine
            command: ["/bin/date"]
  prow-clarketm/sample:
    - name: test-presubmit3
      decorate: true
      always_run: true
      skip_report: false
      spec:
        containers:
          - image: alpine
            command: ["/bin/date"]


