prowjob_namespace: default
pod_namespace: test-pods
plank:
  default_decoration_config:
    utility_images: # using the tag we identified above
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190715-1dacc7e01"
      initupload: "gcr.io/k8s-prow/initupload:v20190715-1dacc7e01"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190715-1dacc7e01"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190715-1dacc7e01"
    gcs_configuration:
      bucket: prow-artifacts # the bucket we just made
      path_strategy: explicit
    gcs_credentials_secret: gcs-credentials # the secret we just made
periodics:
  - interval: 10m
    name: echo-test
    decorate: true
    spec:
      containers:
        - image: alpine
          command: ["/bin/date"]
postsubmits:
  YOUR_ORG/YOUR_REPO:
    - name: test-postsubmit
      decorate: true
      spec:
        containers:
          - image: alpine
            command: ["/bin/printenv"]
presubmits:
  YOUR_ORG/YOUR_REPO:
    - name: test-presubmit
      decorate: true
      always_run: true
      skip_report: false
      spec:
        containers:
          - image: alpine
            command: ["/bin/printenv"]
