---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: deck-private
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: deck-private
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deck-private
subjects:
  - kind: ServiceAccount
    name: deck-private
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: test-pods
  name: deck-private
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deck-private
subjects:
  - kind: ServiceAccount
    name: deck-private
    namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: deck-private
rules:
  - apiGroups:
      - prow.k8s.io
    resources:
      - prowjobs
    verbs:
      - get
      - list
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: test-pods
  name: deck-private
rules:
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deck-private
  labels:
    app: deck-private
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deck-private
  template:
    metadata:
      labels:
        app: deck-private
    spec:
      serviceAccountName: deck-private
      terminationGracePeriodSeconds: 30
      containers:
        - name: deck-private
          image: gcr.io/k8s-prow/deck:v20191101-c5bcba610
          ports:
            - name: http
              containerPort: 8080
          args:
            - --config-path=/etc/config/config.yaml
            - --hook-url=http://hook:8888/plugin-help
            - --redirect-http-to=prow-private.travismclarke.com
            - --kubeconfig=/etc/kubeconfig/config
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
            - mountPath: /etc/kubeconfig
              name: kubeconfig
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 3
            timeoutSeconds: 600
        - name: oauth2-proxy
          image: quay.io/pusher/oauth2_proxy:v4.0.0
          ports:
            - containerPort: 4180
              protocol: TCP
          args:
            - --provider=github
            - --github-org=prow-clarketm
            - --http-address=0.0.0.0:4180
            - --upstream=http://localhost:8080
            - --email-domain=*
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: deck-oauth-proxy
                  key: clientID
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: deck-oauth-proxy
                  key: clientSecret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: deck-oauth-proxy
                  key: cookieSecret
            - name: OAUTH2_PROXY_COOKIE_DOMAIN
              value: prow-private.travismclarke.com
      volumes:
        - name: config
          configMap:
            name: private-config
        - name: kubeconfig
          secret:
            defaultMode: 420
            secretName: kubeconfig
---
apiVersion: v1
kind: Service
metadata:
  name: deck-private
spec:
  selector:
    app: deck-private
  ports:
    - port: 80
      targetPort: 4180
  type: NodePort